config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resource :order, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  belongs_to :product

  validates :quantity, numericality: { only_integer: true, greater_than: 0 }

  delegate :name, to: :user, prefix: true

  after_create :send_reservation_email

  private

  def send_reservation_email
    ReservationMailer.order_email(self).deliver_later
  end

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :orders, dependent: :destroy

  validates :serial_number, :short_description, presence: true
  validates :serial_number, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord

  devise :omniauthable, omniauth_providers: %i[facebook]

  validates :email, :uid, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
    end
  end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base

  self.responder = ApplicationResponder

  protect_from_forgery with: :exception

  respond_to :html
  responders :flash

  protected

  def new_session_path(scope)
    root_path
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!

  def new
    @order = Order.new
  end

  def create
    @order = Order.create(order_params)
    respond_with(@order, location: root_path)
  end

  private

  def order_params
    params
      .require(:order)
      .permit(:quantity, :observation, :product_id)
      .merge(user_id: current_user.id)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user, event: :authentication
    set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = t('app_base_title')
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end

end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/landing/index.slim
div class='center jumbotron'
  
  h1 = t('.title')

  h2 = t('.subtitle')
  
  div class='row'
    div class='col-sm'
      = link_to t('.order_link'), new_order_path, class: 'btn btn-lg btn-primary'
    - unless user_signed_in?
      div class='col-sm'
        = link_to t('.facebook_sign_in_button'), user_facebook_omniauth_authorize_path, class: 'btn btn-lg btn-secondary'

app/views/layouts/application.slim
doctype html
html
  head
    title = full_title(yield(:title))
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'
  body
    div class='container'
      - flash.each do |key, value|
        div class="alert alert-#{key}"
          = value
      = yield

app/views/orders/_form.slim
= simple_form_for @order, url: order_path do |f|
  = f.association :product, label_method: :short_description, include_blank: false
  = f.input :quantity
  = f.input :observation

  = f.button :submit

app/views/orders/new.slim
- provide(:title, t('.title'))

h1 = t('.title')

= render 'form'